ignore:
  - "app/src/main/java/com/example/witsly/Adapters/CommentsAdapter.java"
  - "app/src/main/java/com/example/witsly/Adapters/AnswerAdapter.java"
  - "app/src/main/java/com/example/witsly/Fragments/ProfileFragment.java"
  - "app/src/main/java/com/example/witsly/Fragments/ViewQuestion.java"
  - "app/src/main/java/com/example/witsly/Firebase/FirebaseActions.java"







  


  






